services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    container_name: skinet-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:7-alpine
    container_name: skinet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  sql-data:
  redis-data:
